version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: rose_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: rose_user
      POSTGRES_PASSWORD: rose_password
      POSTGRES_DB: rose_db
      POSTGRES_INITDB_ARGS: "-E UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rose_user -d rose_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local